In [1]:
import pandas as pd

In [6]:
members = pd.read_csv('members.csv')
purchase = pd.read_csv('purchase.csv')

In [7]:
members

  customer_id member_since membership_level
0        C001     5/1/2023             Gold
1        C002   11/15/2023           Silver
2        C004    1/10/2024             Gold

In [8]:
purchase

  transaction_id customer_id  amount transaction_date
0          T1001        C001   120.5        3/15/2024
1          T1002        C002   200.0        3/15/2024
2          T1003        C001   300.0        3/16/2024
3          T1004        C003    50.0        3/17/2024

In [9]:
df = purchase.merge(members,on='customer_id', how='inner')

In [10]:
df

,transaction_id,customer_id,amount,transaction_date,member_since,membership_level
0,T1001,C001,120.5,3/15/2024,5/1/2023,Gold
1,T1002,C002,200.0,3/15/2024,11/15/2023,Silver
2,T1003,C001,300.0,3/16/2024,5/1/2023,Gold

In [11]:
gold_member = df[df['membership_level'] == 'Gold'] 
gold_member

,transaction_id,customer_id,amount,transaction_date,member_since,membership_level
0,T1001,C001,120.5,3/15/2024,5/1/2023,Gold
2,T1003,C001,300.0,3/16/2024,5/1/2023,Gold

In [14]:
total_spent = gold_member.groupby('customer_id')['amount'].sum().reset_index()
total_spent

  customer_id  amount
0        C001   420.5

In [17]:
final_df = total_spent.merge(members,on = 'customer_id')
final_df

  customer_id  amount member_since membership_level
0        C001   420.5     5/1/2023             Gold

In [19]:
final_df = final_df[final_df['amount']>250]
final_df

  customer_id  amount member_since membership_level
0        C001   420.5     5/1/2023             Gold