In [192]:
import pandas as pd

In [213]:
df = pd.read_csv("C:\\Users\\ajith\\Desktop\\jithesh\\Projects\\DE\\reviews.csv")
df

   review_id user_id  rating                       review_text review_date
0       R001    U001     5.0                Excellent quality!    1-Mar-24
1       R002    U002     4.0     Good product, value for money    2-Mar-24
2       R003    U003     NaN                               NaN    3-Mar-24
3       R004    U004     2.0                       This is bad    4-Mar-24
4       R005    U005     1.0                    Not bad at all    5-Mar-24
5       R006    U006     3.0  Very satisfied with the purchase    6-Mar-24
6       R007    U007     6.0                 best product ever    7-Mar-24
7       R008    U008     4.0              BAD customer support    8-Mar-24
8       R009    U009     2.0                   Average product    9-Mar-24
9       R010    U010     5.0               Absolutely amazing!   10-Mar-24
10      R011    U011     3.0         bad quality for the price   11-Mar-24
11      R012    U012     5.0                          Perfect!   12-Mar-24
12      R013    U013     NaN                               NaN   13-Mar-24

In [217]:
df.dropna(subset=['rating','review_text'],inplace = True)

In [218]:
df

   review_id user_id  rating                       review_text review_date
0       R001    U001     5.0                Excellent quality!    1-Mar-24
1       R002    U002     4.0     Good product, value for money    2-Mar-24
3       R004    U004     2.0                       This is bad    4-Mar-24
4       R005    U005     1.0                    Not bad at all    5-Mar-24
5       R006    U006     3.0  Very satisfied with the purchase    6-Mar-24
6       R007    U007     6.0                 best product ever    7-Mar-24
7       R008    U008     4.0              BAD customer support    8-Mar-24
8       R009    U009     2.0                   Average product    9-Mar-24
9       R010    U010     5.0               Absolutely amazing!   10-Mar-24
10      R011    U011     3.0         bad quality for the price   11-Mar-24
11      R012    U012     5.0                          Perfect!   12-Mar-24

In [219]:
df.dtypes

review_id       object
user_id         object
rating         float64
review_text     object
review_date     object
dtype: object

In [220]:
df['rating'] = df['rating'].astype(int)
df

   review_id user_id  rating                       review_text review_date
0       R001    U001       5                Excellent quality!    1-Mar-24
1       R002    U002       4     Good product, value for money    2-Mar-24
3       R004    U004       2                       This is bad    4-Mar-24
4       R005    U005       1                    Not bad at all    5-Mar-24
5       R006    U006       3  Very satisfied with the purchase    6-Mar-24
6       R007    U007       6                 best product ever    7-Mar-24
7       R008    U008       4              BAD customer support    8-Mar-24
8       R009    U009       2                   Average product    9-Mar-24
9       R010    U010       5               Absolutely amazing!   10-Mar-24
10      R011    U011       3         bad quality for the price   11-Mar-24
11      R012    U012       5                          Perfect!   12-Mar-24

In [221]:
filtered_df = df[df['rating'] <= 1]
print(filtered_df)

  review_id user_id  rating     review_text review_date
4      R005    U005       1  Not bad at all    5-Mar-24

In [225]:
filtered_df1 = df[df['rating'] > 5]
filtered_df1

  review_id user_id  rating        review_text review_date sentiment
6      R007    U007       6  best product ever    7-Mar-24  Positive

In [226]:
df['sentiment']= df['review_text'].apply(lambda Text:'Negative' if 'bad' in Text.lower() else 'Positive')
df

,review_id,user_id,rating,review_text,review_date,sentiment
0,R001,U001,5,Excellent quality!,1-Mar-24,Positive
1,R002,U002,4,"Good product, value for money",2-Mar-24,Positive
3,R004,U004,2,This is bad,4-Mar-24,Negative
4,R005,U005,1,Not bad at all,5-Mar-24,Negative
5,R006,U006,3,Very satisfied with the purchase,6-Mar-24,Positive
6,R007,U007,6,best product ever,7-Mar-24,Positive
7,R008,U008,4,BAD customer support,8-Mar-24,Negative
8,R009,U009,2,Average product,9-Mar-24,Positive
9,R010,U010,5,Absolutely amazing!,10-Mar-24,Positive
10,R011,U011,3,bad quality for the price,11-Mar-24,Negative
11,R012,U012,5,Perfect!,12-Mar-24,Positive

In [227]:
df.to_csv('cleaned_reviews.csv', index=False)