In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('users.csv')
df

   user_id   name              email last_updated
0     U001  Alice  alice@example.com     1-Mar-24
1     U002    Bob    bob@example.com     5-Mar-24
2     U003  Alice  alice@example.com    10-Mar-24
3     U004  David  david@example.com     8-Mar-24
4     U005    Eve    eve@example.com     2-Mar-24
5     U006  Frank  frank@example.com     3-Mar-24
6     U007  Grace  grace@example.com     9-Mar-24
7     U008   Hank   hank@example.com     7-Mar-24
8     U009    Bob    bob@example.com    12-Mar-24
9     U010    Ivy    ivy@example.com     6-Mar-24
10    U011   Jake   jake@example.com     4-Mar-24

In [9]:
df.sort_values(by='last_updated', ascending= False)
df

   user_id   name              email last_updated
0     U001  Alice  alice@example.com     1-Mar-24
1     U002    Bob    bob@example.com     5-Mar-24
2     U003  Alice  alice@example.com    10-Mar-24
3     U004  David  david@example.com     8-Mar-24
4     U005    Eve    eve@example.com     2-Mar-24
5     U006  Frank  frank@example.com     3-Mar-24
6     U007  Grace  grace@example.com     9-Mar-24
7     U008   Hank   hank@example.com     7-Mar-24
8     U009    Bob    bob@example.com    12-Mar-24
9     U010    Ivy    ivy@example.com     6-Mar-24
10    U011   Jake   jake@example.com     4-Mar-24

In [16]:
df.drop_duplicates(subset=['email'], keep='first', inplace=True)
df

   user_id   name              email last_updated
0     U001  Alice  alice@example.com     1-Mar-24
1     U002    Bob    bob@example.com     5-Mar-24
3     U004  David  david@example.com     8-Mar-24
4     U005    Eve    eve@example.com     2-Mar-24
5     U006  Frank  frank@example.com     3-Mar-24
6     U007  Grace  grace@example.com     9-Mar-24
7     U008   Hank   hank@example.com     7-Mar-24
9     U010    Ivy    ivy@example.com     6-Mar-24
10    U011   Jake   jake@example.com     4-Mar-24

In [17]:
df.to_csv('cleaned_users.csv', index = False)